### ISSUE TITLE
error during generate

### ISSUE THREAD

**Issue by mhf-ir** [clean/phpdoc-md#12]
Error:
```
./vendor/bin/phpdoc-md

Fatal error: Clean\PhpDocMd\Markdown\GitHub\ClassInfo::__toString -> InvalidArgumentException: Expected a string. Got: ReflectionMethod in /app/app/vendor/webmozart/assert/src/Assert.php:1181
Stack trace:
#0 /app/app/vendor/webmozart/assert/src/Assert.php(194): Webmozart\Assert\Assert::reportInvalidArgument('Expected a stri...')
#1 /app/app/vendor/phpdocumentor/reflection-docblock/src/DocBlock.php(59): Webmozart\Assert\Assert::string(Object(ReflectionMethod))
#2 /app/app/vendor/clean/phpdoc-md/src/ClassParser.php(58): phpDocumentor\Reflection\DocBlock->__construct(Object(ReflectionMethod))
#3 /app/app/vendor/clean/phpdoc-md/src/ClassParser.php(50): Clean\PhpDocMd\ClassParser->getMethodDetails(Object(ReflectionMethod))
#4 /app/app/vendor/clean/phpdoc-md/src/Markdown/ClassInfo.php(32): Clean\PhpDocMd\ClassParser->getMethodsDetails()
#5 /app/app/vendor/clean/view/src/AbstractView.php(92): Clean\PhpDocMd\Markdown\ClassInfo->render()
#6 [internal function]: Clean\View\AbstractView->__toString()
#7 /app/app/vendor/clean/phpdoc- in /app/app/vendor/clean/view/src/AbstractView.php on line 108

Call Stack:
    0.0002     406448   1. {main}() /app/app/vendor/clean/phpdoc-md/bin/phpdoc-md:0
    0.0038     845184   2. file_put_contents() /app/app/vendor/clean/phpdoc-md/bin/phpdoc-md:73
    0.0039     845776   3. Clean\PhpDocMd\Markdown\GitHub\ClassInfo->__toString() /app/app/vendor/clean/phpdoc-md/bin/phpdoc-md:73
    0.0078    1197848   4. trigger_error() /app/app/vendor/clean/view/src/AbstractView.php:108
```

```
php -v
PHP 7.2.10-0ubuntu0.18.04.1 (cli) (built: Sep 13 2018 13:45:02) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.10-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.7.0beta1, Copyright (c) 2002-2018, by Derick Rethans
```

```php
<?php

namespace App\Controller;

use Symfony\Component\HttpFoundation\JsonResponse;
use Swagger\Annotations as SWG;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Example_Class is a sample class for demonstrating PHPDoc
 *
 * Example_Class is a class that has no real actual code, but merely
 * exists to help provide people with an understanding as to how the
 * various PHPDoc tags are used.
 */
class TestController
{

    /**
     * List the rewards of the specified user.
     *
     * This call takes into account all confirmed awards, but not pending or refused awards.
     *
     * @Route("/api/test", methods={"GET"})
     * @SWG\Response(
     *     response=200,
     *     description="Returns the rewards of an user",
     *     @SWG\Schema(
     *         type="string",
     *     )
     * )
     * @SWG\Tag(name="rewards")
     *
     * @return JsonResponse
     */
    public function number(): JsonResponse
    {
        $number = mt_rand(0, 100);

        return new JsonResponse($number);
    }
}

```

**Comment by peengle** [comment]
This has been fixed in the latest release
